### ISSUE TITLE
Ben's list of to-do's to make the Geotiff bit better

### ISSUE THREAD

**Issue by burningsage** [emerald-geomodelling/disco-tif#3]
- [ ] what if data doesn't have a no-data-value? make a fix
- [ ] test all data min-max ranges for the colormap generator
- [x] build look-up-table (lut) writer
- [x] build hill-shade maker
- [ ] emerald-geomodelling/disco-tif#4
- [ ] emerald-geomodelling/disco-tif#5
- [ ] emerald-geomodelling/disco-tif#6
- [ ] can make a gltf surface from the geotiff?
- [ ] #8
- [ ] #9
- [ ] #10
